-- Add readable_id to tickets table

-- 1. Add column with auto-incrementing identity (starting at 1000)
alter table tickets 
add column if not exists readable_id bigint generated by default as identity (start with 1000);

-- 2. Create index for fast lookup
create index if not exists tickets_readable_id_idx on tickets(readable_id);
